### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getGroup'

### ISSUE THREAD

**Issue by yzongy** [neilswainston/SbmlToSbol#3]
Hi Neil,

I am trying to convert the yeast genome-scale metabolic model to SBOL with the galaxy tool, but something went wrong there.

Is there any way to fix that?

> Traceback (most recent call last):
  File "/galaxy/database/dependencies/_conda/envs/__sbml2sbol@0.1.12/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/galaxy/database/dependencies/_conda/envs/__sbml2sbol@0.1.12/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/galaxy/database/dependencies/_conda/envs/__sbml2sbol@0.1.12/lib/python3.7/site-packages/sbml2sbol/__main__.py", line 25, in <module>
    entry_point()
  File "/galaxy/database/dependencies/_conda/envs/__sbml2sbol@0.1.12/lib/python3.7/site-packages/sbml2sbol/__main__.py", line 20, in entry_point
    uniprotID_key=args.uniprotID_key
  File "/galaxy/database/dependencies/_conda/envs/__sbml2sbol@0.1.12/lib/python3.7/site-packages/sbml2sbol/converter.py", line 77, in convert
    uniprotID_key=uniprotID_key
  File "/galaxy/database/dependencies/_conda/envs/__sbml2sbol@0.1.12/lib/python3.7/site-packages/sbml2sbol/converter.py", line 109, in _read_sbml
    rp_pathway = document.model.getPlugin('groups').getGroup(pathway_id)
AttributeError: 'NoneType' object has no attribute 'getGroup'

**Comment by breakthewall** [comment]
Hi,

actually the tool is a little bit misnamed since it extracts UniProt IDs of enzymes that catalyze the reactions in an heterologous pathway stored in an enriched SBML format. And I guess this is not what you try to do.

Best regards,
Joan
